/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * BaseContainer.java
 *
 * Created on Nov 14, 2012, 7:33:36 PM
 */
package SimpleItemEnterInterface;

import Reporting.Database;
import Reporting.SearchableDatabase;
import ValidationFormBox.loginPanel;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;

/**
 *
 * @author paradise lost
 */
public class BaseContainer extends javax.swing.JFrame {

    /** Creates new form BaseContainer */
    public BaseContainer() throws SQLException, IOException {
        databaseForm=new Database();
        up=new UserProgram();
        SearchableD=new SearchableDatabase();
        initComponents();
        
        jolabel.setIcon(new ImageIcon(ImageIO.read(new File("kadian.jpg"))));
        jolabel.setVisible(false);
        jolabel.setVisible(true);
        
        try {
    for (LookAndFeelInfo info : UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
            UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    // If Nimbus is not available, you can set the GUI to another look and feel.
}
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jolabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ControlMenu = new javax.swing.JMenu();
        NewTransactionMenu = new javax.swing.JMenuItem();
        userProgramMenu = new javax.swing.JMenuItem();
        ViewTransactionMenu = new javax.swing.JMenu();
        InventoryButton = new javax.swing.JMenuItem();
        SearchableDatabase = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        loginMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setForeground(new java.awt.Color(0, 51, 204));
        setLocationByPlatform(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(204, 0, 204));
        jLabel2.setText("rabindra.kharel@gmail.com");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 690, 160, 20));

        jLabel3.setForeground(new java.awt.Color(0, 0, 255));
        jLabel3.setText("Product No : 0000001A");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 690, -1, 20));

        jLabel4.setForeground(new java.awt.Color(204, 0, 204));
        jLabel4.setText("Rabindra Kharel");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 690, 100, 20));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 720, 580, 20));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 690, 580, 10));

        jLabel5.setForeground(new java.awt.Color(204, 0, 204));
        jLabel5.setText("Developed By : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 690, 90, 20));
        getContentPane().add(jolabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 600, 310));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("DATA REPORTING ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 530, 370, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 51, 255));
        jLabel6.setText("DATA ENTRY ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, 260, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 51, 255));
        jLabel7.setText("DATA VALIDATION ");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, 370, 60));

        ControlMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        ControlMenu.setForeground(new java.awt.Color(0, 0, 102));
        ControlMenu.setText("PRODUCTS");
        ControlMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        NewTransactionMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        NewTransactionMenu.setText("New Products ");
        NewTransactionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NewTransactionMenuActionPerformed(evt);
            }
        });
        ControlMenu.add(NewTransactionMenu);

        userProgramMenu.setText("Edit Price | Stock");
        userProgramMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userProgramMenuActionPerformed(evt);
            }
        });
        ControlMenu.add(userProgramMenu);

        jMenuBar1.add(ControlMenu);

        ViewTransactionMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(1));
        ViewTransactionMenu.setForeground(new java.awt.Color(0, 0, 102));
        ViewTransactionMenu.setText("        View          ");
        ViewTransactionMenu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        InventoryButton.setText("Database");
        InventoryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InventoryButtonActionPerformed(evt);
            }
        });
        ViewTransactionMenu.add(InventoryButton);

        SearchableDatabase.setText("Searchable Database");
        SearchableDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchableDatabaseActionPerformed(evt);
            }
        });
        ViewTransactionMenu.add(SearchableDatabase);

        jMenuBar1.add(ViewTransactionMenu);

        jMenu4.setBorder(javax.swing.BorderFactory.createBevelBorder(0));
        jMenu4.setForeground(new java.awt.Color(0, 0, 102));
        jMenu4.setText("      Settings    ");
        jMenu4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        loginMenu.setText("Admin Login/logout");
        loginMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginMenuActionPerformed(evt);
            }
        });
        jMenu4.add(loginMenu);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NewTransactionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NewTransactionMenuActionPerformed
        // TODO add your handling code here:
       // AdminFrm.setVisible(true);  
    if(isuser)
    {
//        if(purchaseCount!=0)
//        {  purchaseCount=0;
//            getContentPane().remove(purchaseForm);   
//            }
        if(loginCount!=0)
        {   loginCount=0;
            getContentPane().remove(loginForm);   
                    }
          if(userProgramCount!=0)
        {
        userProgramCount=0;
            getContentPane().remove(up);
        }
        if(billCount==0)
        {   try {
                AdminFrm=new AdminProgram();
           getContentPane().add(AdminFrm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 1800));
              billCount=1;
            } catch (IOException ex) {
                Logger.getLogger(BaseContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
   
        } 
         if(databaseReportCount!=0)
        {   databaseReportCount=0;
            getContentPane().remove(databaseForm);   
         }
         if(SearchDbCount!=0)
        {   SearchDbCount=0;
            getContentPane().remove(SearchableD);   
         }
         //SearchDbCount
       
     getContentPane().invalidate();
     getContentPane().validate();
     setVisible(true);  
     getContentPane().repaint();
    }
    else 
         new javax.swing.JOptionPane().showMessageDialog(this,"You are not logged in !! "); 
       
    }//GEN-LAST:event_NewTransactionMenuActionPerformed

    private void loginMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginMenuActionPerformed
      
         jolabel.setVisible(false);
   jLabel6.setVisible(false);
    jLabel7.setVisible(false);
     jLabel1.setVisible(false);
     
        if(billCount!=0)
        {   billCount=0;
            getContentPane().remove(AdminFrm);   
                    }
      
         if(databaseReportCount!=0)
        {   databaseReportCount=0;
            getContentPane().remove(databaseForm);   
                    }
          if(SearchDbCount!=0)
        {   SearchDbCount=0;
            getContentPane().remove(SearchableD);   
         }
           if(userProgramCount!=0)
        {
        userProgramCount=0;
            getContentPane().remove(up);
        }
         
        if(loginCount==0)
        {
        loginForm=new loginPanel();
        getContentPane().add(loginForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 1800));
        loginCount=1;
       
        } 
        
            
     getContentPane().invalidate();
     getContentPane().validate();
    // setVisible(false);
     setVisible(true);   
     getContentPane().repaint();// TODO add your handling code here:
    }//GEN-LAST:event_loginMenuActionPerformed

    private void InventoryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InventoryButtonActionPerformed
      // purchaseForm.setVisible(true);  
       if(isadmin){
        if(billCount!=0)
        {   billCount=0;
            getContentPane().remove(AdminFrm);   
                    }
        if(loginCount!=0)
        {   loginCount=0;
            getContentPane().remove(loginForm);   
                    }
//         if(purchaseCount!=0)
//        {   purchaseCount=0;
//            getContentPane().remove(purchaseForm);   
//                    }
         if(userProgramCount!=0)
        {
        userProgramCount=0;
            getContentPane().remove(up);
        }
          if(SearchDbCount!=0)
        {   SearchDbCount=0;
            getContentPane().remove(SearchableD);   
         }
        if(databaseReportCount==0)
        {
                try {
                    databaseForm=new Database();
                } catch (SQLException ex) {
                    Logger.getLogger(BaseContainer.class.getName()).log(Level.SEVERE, null, ex);
                }
        getContentPane().add(databaseForm, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 1800));
        databaseReportCount=1;
        
        } 
        
            
     getContentPane().invalidate();
     getContentPane().validate();
    // setVisible(false);
     setVisible(true);   
     getContentPane().repaint();// TODO add your handling code here:
       }
       else
           new javax.swing.JOptionPane().showMessageDialog(this,"Log in as Administrator ! "); 
           // TODO add your handling code here:
    }//GEN-LAST:event_InventoryButtonActionPerformed

    private void userProgramMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userProgramMenuActionPerformed
 if(isuser){
        if(billCount!=0)
        {   billCount=0;
            getContentPane().remove(AdminFrm);   
                    }
//         if(purchaseCount!=0)
//        {   purchaseCount=0;
//            getContentPane().remove(purchaseForm);   
//             }
//           if(SearchDbCount!=0)
//        {   SearchDbCount=0;
//            getContentPane().remove(SearchableD);   
//         }
         if(databaseReportCount!=0)
        {   databaseReportCount=0;
            getContentPane().remove(databaseForm);   
                    }
         if(loginCount!=0)
        {   loginCount=0;
            getContentPane().remove(loginForm);   
         }
         
            if(SearchDbCount!=0)
        {   SearchDbCount=0;
            getContentPane().remove(SearchableD);   
         }
         
        if(userProgramCount==0)
        {
            try {
                up=new UserProgram();
        getContentPane().add(up, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 1800));
        userProgramCount=1;
            } catch (SQLException ex) {
                Logger.getLogger(BaseContainer.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(BaseContainer.class.getName()).log(Level.SEVERE, null, ex);
            }
        } 
        
            
     getContentPane().invalidate();
     getContentPane().validate();
    // setVisible(false);
     setVisible(true);   
     getContentPane().repaint();
 }
 else
           new javax.swing.JOptionPane().showMessageDialog(this,"Log in as User ! "); 
          // TODO add your handling code here:
    }//GEN-LAST:event_userProgramMenuActionPerformed

    private void SearchableDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchableDatabaseActionPerformed
   jolabel.setVisible(false);
   jLabel6.setVisible(false);
    jLabel7.setVisible(false);
     jLabel1.setVisible(false);
        
//        if(isadmin){
        if(billCount!=0)
        {   billCount=0;
            getContentPane().remove(AdminFrm);   
                    }
        if(loginCount!=0)
        {   loginCount=0;
            getContentPane().remove(loginForm);   
                    }
//         if(purchaseCount!=0)
//        {   purchaseCount=0;
//            getContentPane().remove(purchaseForm);   
//                    }
         if(userProgramCount!=0)
        {
        userProgramCount=0;
            getContentPane().remove(up);
        }
          if(databaseReportCount!=0)
        {   databaseReportCount=0;
            getContentPane().remove(databaseForm);   
                    }
        if(SearchDbCount==0)
        {
                try {
                    SearchableD=new SearchableDatabase();
                } catch (SQLException ex) {
                    Logger.getLogger(BaseContainer.class.getName()).log(Level.SEVERE, null, ex);
                }
        getContentPane().add(SearchableD, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1800, 1800));
       SearchDbCount=1;
        } 
        
            
     getContentPane().invalidate();
     getContentPane().validate();
    // setVisible(false);
     setVisible(true);   
     getContentPane().repaint();// TODO add your handling code here:
//       }
//       else
//           new javax.swing.JOptionPane().showMessageDialog(this,"Log in as Administrator ! "); 
//              // TODO add your handling code here:
    }//GEN-LAST:event_SearchableDatabaseActionPerformed

        
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ControlMenu;
    private javax.swing.JMenuItem InventoryButton;
    private javax.swing.JMenuItem NewTransactionMenu;
    private javax.swing.JMenuItem SearchableDatabase;
    private javax.swing.JMenu ViewTransactionMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jolabel;
    private javax.swing.JMenuItem loginMenu;
    private javax.swing.JMenuItem userProgramMenu;
    // End of variables declaration//GEN-END:variables
    private AdminProgram  AdminFrm= new AdminProgram();  
    private  loginPanel loginForm=new loginPanel();
    private UserProgram up;
    private Database databaseForm;
    private SearchableDatabase SearchableD;
    private int billCount=0;
    private int purchaseCount=0;
    private int loginCount=0;
    private int databaseReportCount=0;
    private int userProgramCount=0;
    private int SearchDbCount=0;
    public static boolean isadmin=false;
    public static boolean isuser=false;
    public static String username="";
    public static String ssn_id="";
}
