/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inventory.java
 *
 * Created on Dec 22, 2012, 8:55:29 AM
 */
package Reporting;

import Model.ItemModel;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paradise lost
 */
public class Database extends javax.swing.JPanel {

    /** Creates new form Inventory */
    public Database() throws SQLException {
        dft=new DefaultTableModel();
        dft.addColumn("Desc");
        dft.addColumn("Item");
        dft.addColumn("Price");
        dft.addColumn("URL");        
        dft.addColumn("Stock");
        ItemModel im=new ItemModel();        
        Vector<Vector<String>> resultSet=im.getAllItemDetails("asc");
        for(Vector<String> list : resultSet)
        {
            dft.addRow(list);
        }
        initComponents();     

           
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 19, -1, 640));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Database");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jButton1.setText("Alphabetical");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 660, 120, -1));

        jButton2.setText("Stock Wise");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 660, 110, -1));

        inventoryTable.setModel(dft);
        jScrollPane2.setViewportView(inventoryTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 638));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
//        try {
//           dft=new DefaultTableModel();
//         dft.addColumn("Desc");
//        dft.addColumn("Item");
//        dft.addColumn("Price");
//        dft.addColumn("URL");        
//        dft.addColumn("Stock");
//        ItemModel im=new ItemModel();        
//        Vector<Vector<String>> resultSet=im.getAllItemDetails();
//        for(Vector<String> list : resultSet)
//        {
//            dft.addRow(list);
//        }
//        inventoryTable.setModel(dft);
//        jScrollPane2.setViewportView(inventoryTable);
//        jScrollPane3.setViewportView(jScrollPane2);
//     this.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 638));
//     this.invalidate();
//     this.validate();
//     setVisible(true);   
//     this.repaint();
//        
//        
//// TODO add your handling code here:
//        } catch (SQLException ex) {
//            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_jButton1ActionPerformed

        private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
//        try {
//         dft=new DefaultTableModel();
//        dft.addColumn("Desc");
//        dft.addColumn("Item");
//        dft.addColumn("Price");
//        dft.addColumn("URL");        
//        dft.addColumn("Stock");
//        ItemModel im=new ItemModel();        
//        Vector<Vector<String>> resultSet=im.getAllItemDetails("asc");
//        for(Vector<String> list : resultSet)
//        {
//            dft.addRow(list);
//        }
//     
//        inventoryTable.setModel(dft);
//        jScrollPane2.setViewportView(inventoryTable);
//        jScrollPane3.setViewportView(jScrollPane2);
//     this.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 750, 638));
//     this.invalidate();
//     this.validate();
//     setVisible(true);   
//     this.repaint();
//        } catch (SQLException ex) {
//            Logger.getLogger(Database.class.getName()).log(Level.SEVERE, null, ex);
//        }
        }//GEN-LAST:event_jButton2ActionPerformed
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable inventoryTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
  DefaultTableModel dft;
}
