/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Inventory.java
 *
 * Created on Dec 22, 2012, 8:55:29 AM
 */
package Reporting;

import SimpleItemEnterInterface.UserProgram;
import Model.ItemModel;
import java.awt.Desktop;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author paradise lost
 */
public class SearchableDatabase extends javax.swing.JPanel {
private ItemModel im;
    /** Creates new form Inventory */
    public SearchableDatabase() throws SQLException {
        dft=new DefaultTableModel();
        dft.addColumn("Desc");
        dft.addColumn("Item");
        dft.addColumn("Price");
        dft.addColumn("URL");        
        dft.addColumn("Stock");
        im=new ItemModel();        
        Vector<Vector<String>> resultSet=im.getAllItemDetails("asc");
        for(Vector<String> list : resultSet)
        {
            dft.addRow(list);
        }
        initComponents();     

           
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        inventoryTable1 = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        priceLabel = new javax.swing.JLabel();
        stockLabel = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        itemLabel = new javax.swing.JTextField();
        warningLabel = new javax.swing.JLabel();
        descriptionLabel = new javax.swing.JTextField();
        urlLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        deletemode = new javax.swing.JRadioButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTable.setModel(dft);
        inventoryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(inventoryTable);

        add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, 730, 550));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        inventoryTable1.setModel(dft);
        jScrollPane3.setViewportView(inventoryTable1);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 138, 730, 550));

        jLabel11.setText("PRICE(USD)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, 70, 20));

        jLabel12.setText("URL");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 40, 20));

        priceLabel.setText("0.00 ");
        jPanel1.add(priceLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, 70, 20));

        stockLabel.setText("0");
        jPanel1.add(stockLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 70, 20));

        jLabel4.setText("Stock");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 40, -1));

        itemLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        itemLabel.setText("Type and hit enter");
        itemLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemLabelQuantityMouseExited(evt);
            }
        });
        itemLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemLabelActionPerformed(evt);
            }
        });
        itemLabel.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                itemLabelFocusLost(evt);
            }
        });
        itemLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                itemLabelKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                itemLabelQuantityKeyTyped(evt);
            }
        });
        jPanel1.add(itemLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 200, 30));

        warningLabel.setForeground(new java.awt.Color(255, 51, 51));
        jPanel1.add(warningLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 290, 30));

        descriptionLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionLabelActionPerformed(evt);
            }
        });
        jPanel1.add(descriptionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 200, 30));

        urlLabel.setForeground(new java.awt.Color(0, 51, 255));
        urlLabel.setText("http://");
        urlLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urlLabelMouseClicked(evt);
            }
        });
        jPanel1.add(urlLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 340, 20));

        jLabel2.setText("Item Number");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        jLabel3.setText("Desription");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 70, -1));

        deletemode.setText("Delete Mode");
        jPanel1.add(deletemode, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 780, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void descriptionLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionLabelActionPerformed

    private void itemLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLabelMouseEntered
        if(itemLabel.getText().equals("Type and hit enter"))
        itemLabel.setText("");        // TODO add your handling code here:
    }//GEN-LAST:event_itemLabelMouseEntered

    private void itemLabelQuantityMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemLabelQuantityMouseExited

    }//GEN-LAST:event_itemLabelQuantityMouseExited

    private void itemLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemLabelActionPerformed
        try {
        System.out.println(itemLabel.getText());
        ArrayList<String> str=im.getItemDetailByItemNum(itemLabel.getText());
        System.out.println(str);
        descriptionLabel.setText(str.get(0));
        itemLabel.setText(str.get(1));
        priceLabel.setText(str.get(2));
        priceLabel.setVisible(false);            
        priceLabel.setVisible(true);
        urlLabel.setText(str.get(3));
        urlLabel.setVisible(false);            
        urlLabel.setVisible(true);
        stockLabel.setText(str.get(4));
         stockLabel.setVisible(false);  
        stockLabel.setVisible(true);
              
    } catch (SQLException ex) {
        Logger.getLogger(SearchableDatabase.class.getName()).log(Level.SEVERE, null, ex);
    }
       
    }//GEN-LAST:event_itemLabelActionPerformed

    private void itemLabelFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_itemLabelFocusLost
        if(!itemLabel.getText().matches("[0-9][0-9]*\\.?[0-9]*")) {
            warningLabel.setText("Invalid Item Number !");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_itemLabelFocusLost

    private void itemLabelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemLabelKeyReleased
        if(!itemLabel.getText().matches("[0-9]*\\.?[0-9]*"))
        {      warningLabel.setText("Invalid Item Number !");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        }
        else {
            warningLabel.setText(" ");
            warningLabel.setVisible(false);
            warningLabel.setVisible(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_itemLabelKeyReleased

    private void itemLabelQuantityKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_itemLabelQuantityKeyTyped

    }//GEN-LAST:event_itemLabelQuantityKeyTyped

    private void urlLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urlLabelMouseClicked
    try {
        Desktop.getDesktop().browse(new URI(urlLabel.getText())); 
        
              // TODO add your handling code here:
    } catch (URISyntaxException ex) {
        Logger.getLogger(SearchableDatabase.class.getName()).log(Level.SEVERE, null, ex);
    } catch (IOException ex) {
        Logger.getLogger(SearchableDatabase.class.getName()).log(Level.SEVERE, null, ex);}
    }//GEN-LAST:event_urlLabelMouseClicked

    private void inventoryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryTableMouseClicked

        if(deletemode.isSelected())
        {try {

            System.out.println(inventoryTable.getValueAt(inventoryTable.getSelectedRow(),inventoryTable.getSelectedColumn()));
            im.deleteRecordByItem(inventoryTable.getValueAt(inventoryTable.getSelectedRow(),inventoryTable.getSelectedColumn()).toString());

            dft=new DefaultTableModel();
            dft.addColumn("Desc");
            dft.addColumn("Item");
            dft.addColumn("Price");
            dft.addColumn("URL");
            dft.addColumn("Stock");
            ItemModel im=new ItemModel();
            Vector<Vector<String>> resultSet=im.getAllItemDetails("asc");
            for(Vector<String> list : resultSet)
            {
                dft.addRow(list);
            }

            inventoryTable.setModel(dft);
            jScrollPane2.setViewportView(inventoryTable);
            jScrollPane3.setViewportView(jScrollPane2);
           ((DefaultTableModel)inventoryTable.getModel()).removeRow(inventoryTable.getSelectedRow());
             inventoryTable.setVisible(false);
             inventoryTable.setVisible(true);
             jScrollPane2.setVisible(false);
             jScrollPane2.setVisible(true);
             jScrollPane3.setVisible(false);
              jScrollPane3.setVisible(true);
                    
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(SearchableDatabase.class.getName()).log(Level.SEVERE, null, ex);
        }}
    }//GEN-LAST:event_inventoryTableMouseClicked
       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton deletemode;
    private javax.swing.JTextField descriptionLabel;
    private javax.swing.JTable inventoryTable;
    private javax.swing.JTable inventoryTable1;
    private javax.swing.JTextField itemLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JLabel stockLabel;
    private javax.swing.JLabel urlLabel;
    private javax.swing.JLabel warningLabel;
    // End of variables declaration//GEN-END:variables
  DefaultTableModel dft;
}
